const router = require('express').Router();
const c = require('../controllers/adminController');
const { authenticate, requireAdmin } = require('../middleware/auth');
const { uploadBanner, uploadOrderImage } = require('../middleware/upload');
router.use(authenticate, requireAdmin);
router.get('/dashboard', c.getDashboard);
router.get('/orders', c.getAllOrders);
router.get('/orders/:id', c.getOrder);
router.put('/orders/:id/status', c.updateOrderStatus);
router.put('/orders/:id/payment', c.approvePayment);
router.get('/products', c.getProducts);
router.post('/products', uploadOrderImage.single('image'), c.createProduct);
router.put('/products/:id', uploadOrderImage.single('image'), c.updateProduct);
router.delete('/products/:id', c.deleteProduct);
router.get('/categories', c.getCategories);
router.post('/categories', uploadBanner.single('image'), c.createCategory);
router.get('/banners', c.getBanners);
router.post('/banners', uploadBanner.single('image'), c.createBanner);
router.put('/banners/:id', uploadBanner.single('image'), c.updateBanner);
router.delete('/banners/:id', c.deleteBanner);
router.get('/customers', c.getCustomers);
router.get('/pricing', c.getPricingRules);
router.put('/pricing/:id', c.updatePricingRule);
router.get('/analytics', c.getAnalytics);
module.exports = router;
